
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workprofile_development

test:
  <<: *default
  database: workprofile_test


production:
  <<: *default
  database: workprofile_production
  username: workprofile
  password: <%= ENV['BG_DATABASE_PASSWORD'] %>
